### ISSUE TITLE
【编译报错】 not found for architecture armv7

### ISSUE THREAD

**Issue by spiderjion** [wisdomslab/JPush#1]
我的工程比较老旧，必须支持5.0以上和armv7。
使用<code>pod 'JPushSDK', '~> 1.8.1'</code>
把JPush签下来后，直接编译不会报错。但是在主工程里面引用头文件并且调用其中一个方法（随便一个）后就会报错。
根据排查，发现是pod在link库的时候没link到正确的库上。
PS：非pods方法嵌入到工程是能正常使用的。

**Comment by daheli** [comment]
更新了1.8.2之后用pod集成会有问题。+1
